apiVersion: v1
kind: Service
metadata:
  name: thanos-query
  namespace: monitoring
  labels:
    app: thanos-query
spec:
  selector:
    app: thanos-query
  type: NodePort
  ports:
  - name: http
    port: 10902
    targetPort: http
    nodePort: 30001
