apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanos-query
  namespace: monitoring
  labels:
    app: thanos-query
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thanos-query
  template:
    metadata:
      labels:
        app: thanos-query
    spec:
      containers:
      - name: thanos-query
        image: thanosio/thanos:v0.12.2
        args:
        - query
        - --query.replica-label=replica
        - --log.level=debug
        - --store=10.1.0.61:19191
        - --store=10.1.0.68:19191
        - --store=dnssrv+_grpc._tcp.monitoring.svc:19091
        ports:
        - name: http
          containerPort: 10902
        - name: grpc
          containerPort: 10901
